[workspace]
resolver = "2"
members = [
    "crates/moddef-core",
    "crates/moddef-codegen",
    "crates/moddef-tokio-modbus",
    "conformance",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ModDefOrg/moddef-rs"
rust-version = "1.85"

[workspace.dependencies]
moddef-core = { path = "crates/moddef-core", version = "0.1.0" }
moddef-codegen = { path = "crates/moddef-codegen", version = "0.1.0" }
prost = { version = "0.13", default-features = false, features = ["derive"] }
pbjson = "0.7"
serde = "1"
serde_json = "1"
serde_yaml = "0.9"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "net"] }
