// SPDX-License-Identifier: Apache-2.0

//! Rust client generator (spec §31, §32.4). Emits one standalone module per
//! ModDef document containing:
//!
//!  - real Rust enums with lossless `Unknown(raw)` variants,
//!  - flag structs and packed-field structs per point,
//!  - a `static POINTS: &[PointDesc<'static>]` descriptor table (§32.1),
//!  - a typed `struct <Device><T: Transport>` whose methods drive the codec
//!    core directly over the table — **no `alloc` facade**, so the same
//!    generated client runs on tokio and on embassy,
//!  - §26.2 measurand convenience methods with qualifier enums narrowed to
//!    what the profile actually has.
//!
//! Output is deterministic (document order, no timestamps) and depends only
//! on `moddef-core` (codec + `rt` support). Descriptor contents come from
//! `moddef_core::convert::point_desc`, so the generated table is by
//! construction identical to what the dynamic facade computes at runtime.

use std::collections::BTreeMap;

use proc_macro2::{Ident, Literal, TokenStream};
use quote::{format_ident, quote};

use moddef_core::convert::{desc_bufs, point_desc};
use moddef_core::desc::{
    Access, AddressSpace, ComposedSub, DateTimeEncoding, PointDesc, Rational, ScaleMode,
    StorageType, StringPadding, StringTermination, ValueKind,
};
use moddef_core::schema;

use crate::naming::{ident, pascal, shouty, snake, Scope};

pub struct GeneratedFile {
    /// Suggested file name, e.g. `growatt_sph.rs`.
    pub path: String,
    pub content: String,
}

/// Generate the Rust module(s) for a document (currently always one file).
pub fn generate(doc: &schema::ModDefDocument) -> Vec<GeneratedFile> {
    let tokens = Emitter::new(doc).emit();
    let file = syn::parse2(tokens).expect("generated tokens must parse");
    let body = prettyplease::unparse(&file);
    let content = format!(
        "// Code generated by moddef-codegen from {:?}; DO NOT EDIT.\n{body}",
        doc.doc_id
    );
    let base = if doc.doc_id.is_empty() {
        "moddef_doc".to_owned()
    } else {
        snake(&doc.doc_id)
    };
    vec![GeneratedFile {
        path: format!("{base}.rs"),
        content,
    }]
}

// --------------------------------------------------------------------------- //

struct EnumInfo {
    ident: Ident,
    repr_u16: bool,
}

/// What a generated read method returns / a set method accepts.
#[derive(Clone)]
enum Ret {
    F64,
    Bool,
    U64,
    I64,
    Enum { ident: Ident, repr_u16: bool },
    Flags { ident: Ident, inner: TokenStream },
    Fields { ident: Ident },
    DateTime,
    Str,
    Bytes,
}

impl Ret {
    /// Type token for signatures (Str/Bytes have buffer-based signatures).
    fn ty(&self) -> TokenStream {
        match self {
            Ret::F64 => quote!(f64),
            Ret::Bool => quote!(bool),
            Ret::U64 => quote!(u64),
            Ret::I64 => quote!(i64),
            Ret::Enum { ident, .. } | Ret::Flags { ident, .. } | Ret::Fields { ident } => {
                quote!(#ident)
            }
            Ret::DateTime => quote!(i64),
            Ret::Str => quote!(&str),
            Ret::Bytes => quote!(&[u8]),
        }
    }
}

struct PointPlan {
    index: usize,
    id: String,
    method: Ident,
    set_method: Ident,
    readable: bool,
    writable: bool,
    space: AddressSpace,
    offset: u16,
    model_rel: u16,
    words: usize,
    /// Discovery-slot index when the owning block resolves dynamically.
    discovery: Option<usize>,
    has_na: bool,
    ret: Ret,
    /// point_ids referenced by scale_ref / selector_ref (§10.4/§10.5).
    refs: Vec<String>,
    desc_tokens: TokenStream,
    doc: String,
    measurand: Option<schema::MeasurandRef>,
}

struct Emitter<'a> {
    doc: &'a schema::ModDefDocument,
    top: Scope,
    enums: BTreeMap<String, EnumInfo>,
    items: Vec<TokenStream>,
}

impl<'a> Emitter<'a> {
    fn new(doc: &'a schema::ModDefDocument) -> Self {
        Emitter {
            doc,
            top: Scope::new(),
            enums: BTreeMap::new(),
            items: Vec::new(),
        }
    }

    fn emit(mut self) -> TokenStream {
        self.emit_enums();
        for dev in &self.doc.devices {
            self.emit_device(dev);
        }
        // No inner `#![allow]`: `include!` inside a `mod {}` block rejects
        // inner attributes; consumers put the allow on the wrapping module.
        let items = &self.items;
        quote! {
            use moddef_core::codec::{
                decode, decode_bytes, decode_str, encode, encode_bytes, encode_str,
                validate_write, Ctx,
            };
            use moddef_core::desc::{
                Access, AddressSpace, ComposedSub, DateTimeEncoding, FieldDesc, NaDesc, PointDesc,
                Rational, ScaleMode, ScaleRefDesc, SelectorCaseDesc, SelectorDesc, StorageType,
                StringPadding, StringTermination, ValueKind, WriteDesc,
            };
            use moddef_core::rt;
            use moddef_core::{Error, Reading, Transport, Value};

            #(#items)*
        }
    }

    // ----- document enums (§12) --------------------------------------------- //

    fn emit_enums(&mut self) {
        for e in &self.doc.enums {
            let name = self.top.claim_pascal(&pascal(&e.type_id));
            let eident = ident(&name);
            let repr_u16 = e.values.iter().all(|v| (0..=0xffff).contains(&v.value));
            let repr = if repr_u16 { quote!(u16) } else { quote!(i64) };

            let mut mscope = Scope::new();
            mscope.claim("Unknown");
            let members: Vec<(Ident, i64, String)> = e
                .values
                .iter()
                .map(|v| {
                    let base = if v.name.is_empty() {
                        format!("V{}", v.value)
                    } else {
                        pascal(&v.name)
                    };
                    (ident(&mscope.claim_pascal(&base)), v.value, v.name.clone())
                })
                .collect();

            let lit = |v: i64| {
                if repr_u16 {
                    Literal::u16_suffixed(v as u16)
                } else {
                    Literal::i64_suffixed(v)
                }
            };

            let variants = members.iter().map(|(m, _, _)| quote!(#m));
            // proto3 allows aliased values; only the first alias decodes.
            let mut seen = std::collections::BTreeSet::new();
            let from_arms = members
                .iter()
                .filter(|(_, v, _)| seen.insert(*v))
                .map(|(m, v, _)| {
                    let l = lit(*v);
                    quote!(#l => Self::#m,)
                });
            let value_arms = members.iter().map(|(m, v, _)| {
                let l = lit(*v);
                quote!(Self::#m => #l,)
            });
            let name_arms = members.iter().map(|(m, _, n)| quote!(Self::#m => #n,));

            let doc = doc_attr(&e.description, &e.name);
            self.items.push(quote! {
                #doc
                #[derive(Clone, Copy, Debug, PartialEq, Eq)]
                pub enum #eident {
                    #(#variants,)*
                    /// Any raw value not listed in the profile (lossless, §12).
                    Unknown(#repr),
                }
                impl ::core::convert::From<#repr> for #eident {
                    fn from(v: #repr) -> Self {
                        match v {
                            #(#from_arms)*
                            other => Self::Unknown(other),
                        }
                    }
                }
                impl #eident {
                    pub const fn value(self) -> #repr {
                        match self {
                            #(#value_arms)*
                            Self::Unknown(v) => v,
                        }
                    }
                    pub const fn name(self) -> &'static str {
                        match self {
                            #(#name_arms)*
                            Self::Unknown(_) => "UNKNOWN",
                        }
                    }
                }
            });
            self.enums.insert(
                e.type_id.clone(),
                EnumInfo {
                    ident: eident,
                    repr_u16,
                },
            );
        }
    }

    // ----- device profile ----------------------------------------------------- //

    fn emit_device(&mut self, dev: &schema::DeviceProfile) {
        let class = ident(&self.top.claim_pascal(&pascal(&dev.device_id)));
        let points_name = if self.doc.devices.len() == 1 {
            self.top.claim("POINTS")
        } else {
            self.top
                .claim(&format!("{}_POINTS", shouty(&dev.device_id)))
        };
        let points = ident(&points_name);

        // Discovery slots: one cache entry per block that resolves dynamically.
        let mut discovery_blocks: Vec<&schema::RegisterBlock> = Vec::new();
        let mut slot_of: BTreeMap<&str, usize> = BTreeMap::new();
        for b in &dev.blocks {
            if b.discovery.is_some() {
                slot_of.insert(&b.block_id, discovery_blocks.len());
                discovery_blocks.push(b);
            }
        }

        let mut methods = Scope::new();
        methods.claim("new");
        methods.claim("transport");
        methods.claim("into_transport");
        for i in 0..discovery_blocks.len() {
            methods.claim(&format!("resolve_block_{i}"));
        }

        let mut plans: Vec<PointPlan> = Vec::new();
        for b in &dev.blocks {
            for p in &b.points {
                let index = plans.len();
                let bufs = desc_bufs(p);
                let d = point_desc(p, b.space(), &bufs);

                let ret = self.ret_kind(p, &d, &mut Scope::new());
                let mut refs = Vec::new();
                if let Some(sr) = p.transform.as_ref().and_then(|t| t.scale_ref.as_ref()) {
                    refs.push(sr.point_id.clone());
                }
                if let Some(sel) = &p.selector_ref {
                    refs.push(sel.point_id.clone());
                }

                let mut doc = p.name.clone();
                if !p.description.is_empty() {
                    if !doc.is_empty() {
                        doc.push_str(" — ");
                    }
                    doc.push_str(&p.description);
                }

                plans.push(PointPlan {
                    index,
                    id: p.point_id.clone(),
                    method: ident(&methods.claim(&snake(&p.point_id))),
                    set_method: ident(&methods.claim(&format!("set_{}", snake(&p.point_id)))),
                    readable: d.readable(),
                    writable: d.writable(),
                    space: d.space,
                    offset: d.offset,
                    model_rel: d.model_relative_offset,
                    words: d.words(),
                    discovery: slot_of.get(b.block_id.as_str()).copied(),
                    has_na: !d.na.is_empty(),
                    ret,
                    refs,
                    desc_tokens: desc_tokens(&d),
                    doc,
                    measurand: p.measurand.clone(),
                });
            }
        }
        let by_id: BTreeMap<&str, usize> = plans.iter().map(|p| (p.id.as_str(), p.index)).collect();

        // Descriptor table (§32.1 catalog; usable standalone on no_std).
        let descs = plans.iter().map(|p| &p.desc_tokens);
        let table_doc = format!(
            "Point descriptors for device profile {:?} (spec §32.1).",
            dev.device_id
        );
        self.items.push(quote! {
            #[doc = #table_doc]
            pub static #points: &[PointDesc<'static>] = &[#(#descs),*];
        });

        // Typed device struct.
        let n_slots = discovery_blocks.len();
        let struct_doc = format!(
            "{} {} — typed client for device profile {:?}.",
            dev.vendor, dev.model, dev.device_id
        );

        let resolve_fns = discovery_blocks.iter().enumerate().map(|(slot, b)| {
            let rid = format_ident!("resolve_block_{slot}");
            let disc = b.discovery.as_ref().unwrap();
            let space = space_tokens(block_space(b));
            if disc.kind() != schema::DiscoveryKind::Sunspec {
                return quote! {
                    async fn #rid(&mut self) -> Result<u16, Error<T::Error>> {
                        Err(Error::UnsupportedMapping("unsupported discovery kind"))
                    }
                };
            }
            let anchors: Vec<Literal> = if disc.anchor_candidates.is_empty() {
                [40000u16, 50000, 0]
                    .iter()
                    .map(|a| Literal::u16_suffixed(*a))
                    .collect()
            } else {
                disc.anchor_candidates
                    .iter()
                    .map(|a| Literal::u16_suffixed(*a as u16))
                    .collect()
            };
            let model = Literal::u16_suffixed(disc.model_id as u16);
            quote! {
                async fn #rid(&mut self) -> Result<u16, Error<T::Error>> {
                    if let Some(base) = self.model_base[#slot] {
                        return Ok(base);
                    }
                    let base = rt::resolve_sunspec(
                        &mut self.transport,
                        #space,
                        &[#(#anchors),*],
                        #model,
                    )
                    .await?;
                    self.model_base[#slot] = Some(base);
                    Ok(base)
                }
            }
        });

        let point_methods: Vec<TokenStream> = plans
            .iter()
            .map(|p| self.point_methods(p, &plans, &by_id, &points))
            .collect();

        let measurand_methods = self.measurand_methods(&plans, &mut methods);

        self.items.push(quote! {
            #[doc = #struct_doc]
            pub struct #class<T: Transport> {
                pub transport: T,
                model_base: [Option<u16>; #n_slots],
            }

            impl<T: Transport> #class<T> {
                pub fn new(transport: T) -> Self {
                    Self { transport, model_base: [None; #n_slots] }
                }

                pub fn into_transport(self) -> T {
                    self.transport
                }

                #(#resolve_fns)*
                #(#point_methods)*
                #(#measurand_methods)*
            }
        });
    }

    // ----- per-point methods --------------------------------------------------- //

    fn point_methods(
        &self,
        p: &PointPlan,
        plans: &[PointPlan],
        by_id: &BTreeMap<&str, usize>,
        points: &Ident,
    ) -> TokenStream {
        let mut out = TokenStream::new();
        let idx = p.index;
        let words = p.words;
        let space = space_tokens(p.space);
        let off_expr = offset_expr(p);
        let doc = doc_attr(&p.doc, "");

        // Companion reads for scale_ref / selector_ref (§10.4/§10.5).
        let mut ref_stmts = TokenStream::new();
        let mut ref_pairs = Vec::new();
        for (k, rid) in p.refs.iter().enumerate() {
            let Some(&ri) = by_id.get(rid.as_str()) else {
                continue;
            };
            let rp = &plans[ri];
            let rvar = format_ident!("ref_{k}");
            let rregs = format_ident!("ref_regs_{k}");
            let roffv = format_ident!("ref_off_{k}");
            let rwords = rp.words;
            let rspace = space_tokens(rp.space);
            let roff = offset_expr(rp);
            let ridx = rp.index;
            ref_stmts.extend(quote! {
                let #roffv: u16 = #roff;
                let #rregs: [u16; #rwords] =
                    rt::read_regs(&mut self.transport, #rspace, #roffv).await?;
                let #rvar = rt::ref_int::<T::Error>(
                    decode(&#points[#ridx], &#rregs, &Ctx::EMPTY).map_err(Error::Decode)?,
                )?;
            });
            ref_pairs.push(quote!((#rid, #rvar)));
        }
        let ctx_stmt = if ref_pairs.is_empty() {
            quote! { let ctx = Ctx::EMPTY; }
        } else {
            quote! {
                let refs = [#(#ref_pairs),*];
                let ctx = Ctx { refs: &refs };
            }
        };

        if p.readable {
            let m = &p.method;
            match &p.ret {
                Ret::Str => out.extend(quote! {
                    #doc
                    pub async fn #m<'b>(&mut self, buf: &'b mut [u8])
                        -> Result<&'b str, Error<T::Error>>
                    {
                        let off: u16 = #off_expr;
                        let regs: [u16; #words] =
                            rt::read_regs(&mut self.transport, #space, off).await?;
                        decode_str(&#points[#idx], &regs, buf).map_err(Error::Decode)
                    }
                }),
                Ret::Bytes => out.extend(quote! {
                    #doc
                    pub async fn #m<'b>(&mut self, buf: &'b mut [u8])
                        -> Result<&'b [u8], Error<T::Error>>
                    {
                        let off: u16 = #off_expr;
                        let regs: [u16; #words] =
                            rt::read_regs(&mut self.transport, #space, off).await?;
                        decode_bytes(&#points[#idx], &regs, buf).map_err(Error::Decode)
                    }
                }),
                ret => {
                    let extract = extract_expr(ret);
                    let ty = ret.ty();
                    let (ret_ty, ok_val, na_check) = if p.has_na {
                        (
                            quote!(Reading<#ty>),
                            quote!(Reading::Value(#extract)),
                            quote! {
                                if matches!(v, Value::Unavailable) {
                                    return Ok(Reading::Unavailable(
                                        rt::na_meaning(&#points[#idx], &regs),
                                    ));
                                }
                            },
                        )
                    } else {
                        (quote!(#ty), quote!(#extract), quote!())
                    };
                    out.extend(quote! {
                        #doc
                        pub async fn #m(&mut self) -> Result<#ret_ty, Error<T::Error>> {
                            #ref_stmts
                            #ctx_stmt
                            let off: u16 = #off_expr;
                            let regs: [u16; #words] =
                                rt::read_regs(&mut self.transport, #space, off).await?;
                            let v = decode(&#points[#idx], &regs, &ctx).map_err(Error::Decode)?;
                            #na_check
                            Ok(#ok_val)
                        }
                    });
                }
            }
        }

        if p.writable {
            let sm = &p.set_method;
            let wdoc = format!("Write {:?} (§11.4 constraints validated).", p.id);
            match &p.ret {
                Ret::Str => out.extend(quote! {
                    #[doc = #wdoc]
                    pub async fn #sm(&mut self, v: &str) -> Result<(), Error<T::Error>> {
                        let off: u16 = #off_expr;
                        let mut regs = [0u16; #words];
                        encode_str(&#points[#idx], v, &mut regs).map_err(Error::Encode)?;
                        rt::write_regs(&mut self.transport, #space, off, &regs).await
                    }
                }),
                Ret::Bytes => out.extend(quote! {
                    #[doc = #wdoc]
                    pub async fn #sm(&mut self, v: &[u8]) -> Result<(), Error<T::Error>> {
                        let off: u16 = #off_expr;
                        let mut regs = [0u16; #words];
                        encode_bytes(&#points[#idx], v, &mut regs).map_err(Error::Encode)?;
                        rt::write_regs(&mut self.transport, #space, off, &regs).await
                    }
                }),
                Ret::Fields { .. } => {} // packed windows are read-oriented (§13.1)
                ret => {
                    let ty = ret.ty();
                    let val = value_ctor(ret);
                    out.extend(quote! {
                        #[doc = #wdoc]
                        pub async fn #sm(&mut self, v: #ty) -> Result<(), Error<T::Error>> {
                            let val = #val;
                            validate_write(&#points[#idx], &val).map_err(Error::WriteConstraint)?;
                            #ref_stmts
                            #ctx_stmt
                            let off: u16 = #off_expr;
                            let mut regs = [0u16; #words];
                            encode(&#points[#idx], &val, &ctx, &mut regs).map_err(Error::Encode)?;
                            rt::write_regs(&mut self.transport, #space, off, &regs).await
                        }
                    });
                }
            }
        }

        out
    }

    // ----- measurand convenience (§26.2) --------------------------------------- //

    fn measurand_methods(&mut self, plans: &[PointPlan], methods: &mut Scope) -> Vec<TokenStream> {
        struct Dim {
            label: &'static str,
            get: fn(&schema::MeasurandRef) -> (i32, &'static str),
        }
        let dims: [Dim; 5] = [
            Dim {
                label: "direction",
                get: |m| (m.direction, m.direction().as_str_name()),
            },
            Dim {
                label: "phase",
                get: |m| (m.phase_ref, m.phase_ref().as_str_name()),
            },
            Dim {
                label: "aggregation",
                get: |m| (m.aggregation, m.aggregation().as_str_name()),
            },
            Dim {
                label: "location",
                get: |m| (m.location, m.location().as_str_name()),
            },
            Dim {
                label: "accumulation",
                get: |m| (m.accumulation, m.accumulation().as_str_name()),
            },
        ];

        let mut by_bq: BTreeMap<&str, Vec<&PointPlan>> = BTreeMap::new();
        for p in plans {
            let Some(m) = &p.measurand else { continue };
            if m.base_quantity.is_empty() || !p.readable || matches!(p.ret, Ret::Str | Ret::Bytes) {
                continue;
            }
            by_bq.entry(&m.base_quantity).or_default().push(p);
        }

        let mut out = Vec::new();
        for (bq, pts) in by_bq {
            let name = ident(&methods.claim(&format!("get_{}", snake(bq))));

            if let [p] = pts.as_slice() {
                let m = &p.method;
                let ty = p.ret.ty();
                let ret_ty = if p.has_na {
                    quote!(Reading<#ty>)
                } else {
                    quote!(#ty)
                };
                let doc = format!("Measurand {bq:?} (single matching point: {}).", p.id);
                out.push(quote! {
                    #[doc = #doc]
                    pub async fn #name(&mut self) -> Result<#ret_ty, Error<T::Error>> {
                        self.#m().await
                    }
                });
                continue;
            }

            // All matching points must agree on the return type.
            let sig = |p: &PointPlan| format!("{}/{}", p.ret.ty(), p.has_na);
            if !pts.windows(2).all(|w| sig(w[0]) == sig(w[1])) {
                continue;
            }

            // Which qualifier dimensions actually vary across the points?
            let varying: Vec<&Dim> = dims
                .iter()
                .filter(|d| {
                    pts.iter()
                        .any(|p| (d.get)(p.measurand.as_ref().unwrap()).0 != 0)
                })
                .collect();
            if varying.is_empty() {
                continue; // permanently ambiguous; use the untyped facade
            }

            // Points addressable via the qualifiers: all varying dims nonzero.
            let mut combos: BTreeMap<Vec<i32>, &PointPlan> = BTreeMap::new();
            let mut ambiguous = false;
            for p in &pts {
                let m = p.measurand.as_ref().unwrap();
                let key: Vec<i32> = varying.iter().map(|d| (d.get)(m).0).collect();
                if key.contains(&0) {
                    continue;
                }
                if combos.insert(key, *p).is_some() {
                    ambiguous = true;
                }
            }
            if ambiguous || combos.is_empty() {
                continue;
            }

            // Qualifier enums narrowed to the values present in this group.
            let mut enum_idents = Vec::new();
            let mut variant_of: Vec<BTreeMap<i32, Ident>> = Vec::new();
            for (di, d) in varying.iter().enumerate() {
                let ename = ident(&self.top.claim_pascal(&format!(
                    "{}{}",
                    pascal(bq),
                    pascal(d.label)
                )));
                let mut vals: Vec<(i32, &'static str)> = combos
                    .keys()
                    .map(|k| {
                        let v = k[di];
                        let n = pts
                            .iter()
                            .find_map(|p| {
                                let (val, name) = (d.get)(p.measurand.as_ref().unwrap());
                                (val == v).then_some(name)
                            })
                            .unwrap_or("UNKNOWN");
                        (v, n)
                    })
                    .collect();
                vals.sort_unstable();
                vals.dedup();
                let mut vscope = Scope::new();
                let map: BTreeMap<i32, Ident> = vals
                    .iter()
                    .map(|(v, n)| (*v, ident(&vscope.claim_pascal(&pascal(n)))))
                    .collect();
                let variants = map.values();
                let doc = format!(
                    "Qualifier for [`get_{}`]: {} values present in the profile.",
                    snake(bq),
                    d.label
                );
                self.items.push(quote! {
                    #[doc = #doc]
                    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
                    pub enum #ename { #(#variants),* }
                });
                enum_idents.push(ename);
                variant_of.push(map);
            }

            let params: Vec<TokenStream> = varying
                .iter()
                .zip(&enum_idents)
                .map(|(d, e)| {
                    let a = ident(d.label);
                    quote!(#a: #e)
                })
                .collect();
            let scrutinee: TokenStream = {
                let args: Vec<Ident> = varying.iter().map(|d| ident(d.label)).collect();
                if args.len() == 1 {
                    let a = &args[0];
                    quote!(#a)
                } else {
                    quote!((#(#args),*))
                }
            };
            let arms = combos.iter().map(|(key, p)| {
                let pat: Vec<TokenStream> = key
                    .iter()
                    .zip(&enum_idents)
                    .zip(&variant_of)
                    .map(|((v, e), map)| {
                        let var = &map[v];
                        quote!(#e::#var)
                    })
                    .collect();
                let pat = if pat.len() == 1 {
                    let p0 = &pat[0];
                    quote!(#p0)
                } else {
                    quote!((#(#pat),*))
                };
                let m = &p.method;
                quote!(#pat => self.#m().await,)
            });
            // Wildcard only when the qualifier cross-product exceeds the combos.
            let cross: usize = variant_of.iter().map(|m| m.len()).product();
            let wildcard = if cross > combos.len() {
                quote!(_ => Err(Error::MeasurandNotSupported),)
            } else {
                quote!()
            };

            let p0 = combos.values().next().unwrap();
            let ty = p0.ret.ty();
            let ret_ty = if p0.has_na {
                quote!(Reading<#ty>)
            } else {
                quote!(#ty)
            };
            let doc = format!(
                "Measurand {bq:?} — {} matching points, qualified by {}.",
                pts.len(),
                varying
                    .iter()
                    .map(|d| d.label)
                    .collect::<Vec<_>>()
                    .join(" + "),
            );
            out.push(quote! {
                #[doc = #doc]
                pub async fn #name(&mut self, #(#params),*) -> Result<#ret_ty, Error<T::Error>> {
                    match #scrutinee {
                        #(#arms)*
                        #wildcard
                    }
                }
            });
        }
        out
    }

    // ----- value typing --------------------------------------------------------- //

    fn ret_kind(&mut self, p: &schema::Point, d: &PointDesc<'_>, _scope: &mut Scope) -> Ret {
        match &d.value {
            ValueKind::Decimal | ValueKind::Composed { .. } => Ret::F64,
            ValueKind::Bool => Ret::Bool,
            ValueKind::Uint => Ret::U64,
            ValueKind::Int => Ret::I64,
            ValueKind::DateTime(_) => Ret::DateTime,
            ValueKind::Str { .. } => Ret::Str,
            ValueKind::Bytes => Ret::Bytes,
            ValueKind::Flags(table) => {
                let name = self.top.claim_pascal(&pascal(&p.point_id));
                let fident = ident(&name);
                let bits = d.storage.bits(d.words());
                let inner = if bits <= 16 {
                    quote!(u16)
                } else if bits <= 32 {
                    quote!(u32)
                } else {
                    quote!(u64)
                };
                self.emit_flags_struct(&fident, &inner, table, &p.name);
                Ret::Flags {
                    ident: fident,
                    inner,
                }
            }
            ValueKind::Fields(fields) => {
                let name = self.top.claim_pascal(&pascal(&p.point_id));
                let sident = ident(&name);
                self.emit_fields_struct(&sident, fields, &p.name);
                Ret::Fields { ident: sident }
            }
            ValueKind::Enum => {
                if let Some(schema::value_type::Kind::EnumRef(er)) =
                    p.value_type.as_ref().and_then(|v| v.kind.as_ref())
                {
                    if let Some(info) = self.enums.get(&er.type_id) {
                        return Ret::Enum {
                            ident: info.ident.clone(),
                            repr_u16: info.repr_u16,
                        };
                    }
                }
                // Imported/unknown enum: raw integer, signed if the storage is.
                if d.storage.signed() {
                    Ret::I64
                } else {
                    Ret::U64
                }
            }
        }
    }

    fn emit_flags_struct(
        &mut self,
        fident: &Ident,
        inner: &TokenStream,
        table: &[(u8, &str)],
        pname: &str,
    ) {
        let mut cscope = Scope::new();
        let consts = table.iter().map(|(bit, name)| {
            let c = ident(&cscope.claim(&shouty(name)));
            let b = *bit as u32;
            quote! { pub const #c: Self = Self(1 << #b); }
        });
        let entries = table.iter().map(|(bit, name)| quote!((#bit, #name)));
        let doc = doc_attr(&format!("{pname} — flag set (§13.2)."), "");
        self.items.push(quote! {
            #doc
            #[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
            pub struct #fident(pub #inner);
            impl #fident {
                #(#consts)*
                pub const fn bits(self) -> #inner {
                    self.0
                }
                pub const fn contains(self, other: Self) -> bool {
                    (self.0 & other.0) == other.0
                }
                /// Names of the set flags, ascending bit order.
                pub fn iter_names(self) -> impl Iterator<Item = &'static str> {
                    const TABLE: &[(u8, &str)] = &[#(#entries),*];
                    let bits = self.0 as u64;
                    TABLE
                        .iter()
                        .filter(move |(b, _)| bits & (1u64 << *b as u32) != 0)
                        .map(|(_, n)| *n)
                }
            }
        });
    }

    fn emit_fields_struct(
        &mut self,
        sident: &Ident,
        fields: &[moddef_core::desc::FieldDesc<'_>],
        pname: &str,
    ) {
        let mut fscope = Scope::new();
        let planned: Vec<(Ident, TokenStream, u32, u32)> = fields
            .iter()
            .map(|f| {
                let fi = ident(&fscope.claim(&snake(f.id)));
                let ty = if f.bit_length <= 8 {
                    quote!(u8)
                } else if f.bit_length <= 16 {
                    quote!(u16)
                } else if f.bit_length <= 32 {
                    quote!(u32)
                } else {
                    quote!(u64)
                };
                (fi, ty, f.bit_offset, f.bit_length)
            })
            .collect();
        let defs = planned.iter().map(|(fi, ty, _, _)| quote!(pub #fi: #ty));
        let inits = planned.iter().map(|(fi, ty, off, len)| {
            let mask = if *len >= 64 {
                u64::MAX
            } else {
                (1u64 << len) - 1
            };
            quote!(#fi: ((w >> #off) & #mask) as #ty)
        });
        let doc = doc_attr(&format!("{pname} — packed sub-fields (§13)."), "");
        self.items.push(quote! {
            #doc
            #[derive(Clone, Copy, Debug, PartialEq, Eq)]
            pub struct #sident { #(#defs),* }
            impl ::core::convert::From<u64> for #sident {
                fn from(w: u64) -> Self {
                    Self { #(#inits),* }
                }
            }
        });
    }
}

// ----- token helpers ---------------------------------------------------------- //

fn doc_attr(primary: &str, fallback: &str) -> TokenStream {
    let s = if !primary.is_empty() {
        primary
    } else {
        fallback
    };
    if s.is_empty() {
        quote!()
    } else {
        quote!(#[doc = #s])
    }
}

fn block_space(b: &schema::RegisterBlock) -> AddressSpace {
    match b.space() {
        schema::AddressSpace::Coil => AddressSpace::Coil,
        schema::AddressSpace::DiscreteInput => AddressSpace::DiscreteInput,
        schema::AddressSpace::InputRegister => AddressSpace::InputRegister,
        _ => AddressSpace::HoldingRegister,
    }
}

fn offset_expr(p: &PointPlan) -> TokenStream {
    let off = Literal::u16_suffixed(p.offset);
    match p.discovery {
        Some(slot) => {
            let rid = format_ident!("resolve_block_{slot}");
            let rel = Literal::u16_suffixed(p.model_rel);
            quote!(self.#rid().await? + #rel)
        }
        None => quote!(#off),
    }
}

fn extract_expr(ret: &Ret) -> TokenStream {
    match ret {
        Ret::F64 => quote!(rt::value_f64::<T::Error>(v)?),
        Ret::Bool => quote!(rt::value_bool::<T::Error>(v)?),
        Ret::U64 => quote!(rt::value_u64::<T::Error>(v)?),
        Ret::I64 => quote!(rt::value_i64::<T::Error>(v)?),
        Ret::Enum { ident, repr_u16 } => {
            if *repr_u16 {
                quote!(#ident::from(rt::ref_int::<T::Error>(v)? as u16))
            } else {
                quote!(#ident::from(rt::ref_int::<T::Error>(v)?))
            }
        }
        Ret::Flags { ident, inner } => quote!(#ident(rt::value_flags::<T::Error>(v)? as #inner)),
        Ret::Fields { ident } => quote!(#ident::from(rt::value_fields::<T::Error>(v)?)),
        Ret::DateTime => quote!(rt::value_datetime::<T::Error>(v)?),
        Ret::Str | Ret::Bytes => unreachable!("buffer-based signatures"),
    }
}

fn value_ctor(ret: &Ret) -> TokenStream {
    match ret {
        Ret::F64 => quote!(Value::F64(v)),
        Ret::Bool => quote!(Value::Bool(v)),
        Ret::U64 => quote!(Value::U64(v)),
        Ret::I64 => quote!(Value::I64(v)),
        Ret::Enum { repr_u16, .. } => {
            if *repr_u16 {
                quote!(Value::U64(v.value() as u64))
            } else {
                quote!(Value::I64(v.value()))
            }
        }
        Ret::Flags { .. } => quote!(Value::Flags(v.0 as u64)),
        Ret::DateTime => quote!(Value::DateTime(v)),
        Ret::Fields { .. } | Ret::Str | Ret::Bytes => unreachable!("handled by caller"),
    }
}

fn space_tokens(s: AddressSpace) -> TokenStream {
    match s {
        AddressSpace::Coil => quote!(AddressSpace::Coil),
        AddressSpace::DiscreteInput => quote!(AddressSpace::DiscreteInput),
        AddressSpace::InputRegister => quote!(AddressSpace::InputRegister),
        AddressSpace::HoldingRegister => quote!(AddressSpace::HoldingRegister),
    }
}

fn storage_tokens(s: StorageType) -> TokenStream {
    macro_rules! arm {
        ($($v:ident),*) => {
            match s { $(StorageType::$v => quote!(StorageType::$v)),* }
        };
    }
    arm!(
        Unspecified,
        Bit,
        U16,
        S16,
        U24,
        U32,
        S32,
        U48,
        S48,
        U64,
        S64,
        F32,
        F64,
        StringAscii,
        StringUtf8,
        BytesRaw,
        Bcd,
        Composed
    )
}

fn rational_tokens(r: &Rational) -> TokenStream {
    let n = Literal::i64_suffixed(r.num);
    let d = Literal::i64_suffixed(r.den);
    quote!(Rational { num: #n, den: #d })
}

fn opt_tokens(t: Option<TokenStream>) -> TokenStream {
    match t {
        Some(t) => quote!(Some(#t)),
        None => quote!(None),
    }
}

fn value_kind_tokens(v: &ValueKind<'_>) -> TokenStream {
    match v {
        ValueKind::Decimal => quote!(ValueKind::Decimal),
        ValueKind::Bool => quote!(ValueKind::Bool),
        ValueKind::Uint => quote!(ValueKind::Uint),
        ValueKind::Int => quote!(ValueKind::Int),
        ValueKind::Enum => quote!(ValueKind::Enum),
        ValueKind::Flags(t) => {
            let entries = t.iter().map(|(b, n)| quote!((#b, #n)));
            quote!(ValueKind::Flags(&[#(#entries),*]))
        }
        ValueKind::Fields(fs) => {
            let entries = fs.iter().map(|f| {
                let id = f.id;
                let o = f.bit_offset;
                let l = f.bit_length;
                quote!(FieldDesc { id: #id, bit_offset: #o, bit_length: #l })
            });
            quote!(ValueKind::Fields(&[#(#entries),*]))
        }
        ValueKind::Str {
            padding,
            termination,
        } => {
            let p = match padding {
                StringPadding::None => quote!(StringPadding::None),
                StringPadding::Null => quote!(StringPadding::Null),
                StringPadding::Space => quote!(StringPadding::Space),
            };
            let t = match termination {
                StringTermination::FixedLength => quote!(StringTermination::FixedLength),
                StringTermination::NullTerminated => quote!(StringTermination::NullTerminated),
            };
            quote!(ValueKind::Str { padding: #p, termination: #t })
        }
        ValueKind::Bytes => quote!(ValueKind::Bytes),
        ValueKind::DateTime(e) => {
            let e = match e {
                DateTimeEncoding::EpochSeconds => quote!(DateTimeEncoding::EpochSeconds),
                DateTimeEncoding::EpochMillis => quote!(DateTimeEncoding::EpochMillis),
            };
            quote!(ValueKind::DateTime(#e))
        }
        ValueKind::Composed {
            base,
            mantissa,
            exponent,
        } => {
            let b = Literal::i64_suffixed(*base);
            let sub = |s: &ComposedSub| {
                let ComposedSub {
                    offset,
                    words,
                    bit_offset,
                    bit_length,
                    width_bits,
                    signed,
                } = *s;
                quote!(ComposedSub {
                    offset: #offset,
                    words: #words,
                    bit_offset: #bit_offset,
                    bit_length: #bit_length,
                    width_bits: #width_bits,
                    signed: #signed,
                })
            };
            let m = sub(mantissa);
            let e = sub(exponent);
            quote!(ValueKind::Composed { base: #b, mantissa: #m, exponent: #e })
        }
    }
}

fn desc_tokens(d: &PointDesc<'_>) -> TokenStream {
    let id = d.id;
    let space = space_tokens(d.space);
    let offset = Literal::u16_suffixed(d.offset);
    let model_rel = Literal::u16_suffixed(d.model_relative_offset);
    let lw = Literal::u16_suffixed(d.length_words);
    let storage = storage_tokens(d.storage);
    let value = value_kind_tokens(&d.value);
    let byte_big = d.byte_big;
    let word_big = d.word_big;
    let scale = opt_tokens(d.scale.as_ref().map(rational_tokens));
    let offset_add = opt_tokens(d.offset_add.as_ref().map(rational_tokens));
    let scale_ref = opt_tokens(d.scale_ref.as_ref().map(|sr| {
        let pid = sr.point_id;
        let mode = match sr.mode {
            ScaleMode::Pow10 => quote!(ScaleMode::Pow10),
            ScaleMode::Multiply => quote!(ScaleMode::Multiply),
        };
        let den = Literal::i64_suffixed(sr.denominator);
        quote!(ScaleRefDesc { point_id: #pid, mode: #mode, denominator: #den })
    }));
    let selector = opt_tokens(d.selector.as_ref().map(|sel| {
        let pid = sel.point_id;
        let cases = sel.cases.iter().map(|c| {
            let k = Literal::i64_suffixed(c.key);
            let s = opt_tokens(c.scale.as_ref().map(rational_tokens));
            let o = opt_tokens(c.offset.as_ref().map(rational_tokens));
            quote!(SelectorCaseDesc { key: #k, scale: #s, offset: #o })
        });
        quote!(SelectorDesc { point_id: #pid, cases: &[#(#cases),*] })
    }));
    let na = d.na.iter().map(|n| {
        let raw = Literal::i64_suffixed(n.raw);
        let meaning = n.meaning;
        quote!(NaDesc { raw: #raw, meaning: #meaning })
    });
    let access = match d.access {
        Access::ReadOnly => quote!(Access::ReadOnly),
        Access::WriteOnly => quote!(Access::WriteOnly),
        Access::ReadWrite => quote!(Access::ReadWrite),
        Access::Command => quote!(Access::Command),
    };
    let write = opt_tokens(d.write.as_ref().map(|w| {
        let min = opt_tokens(w.min.as_ref().map(rational_tokens));
        let max = opt_tokens(w.max.as_ref().map(rational_tokens));
        let step = opt_tokens(w.step.as_ref().map(rational_tokens));
        let allowed = w.allowed.iter().map(|a| Literal::i64_suffixed(*a));
        quote!(WriteDesc { min: #min, max: #max, step: #step, allowed: &[#(#allowed),*] })
    }));

    quote! {
        PointDesc {
            id: #id,
            space: #space,
            offset: #offset,
            model_relative_offset: #model_rel,
            length_words: #lw,
            storage: #storage,
            value: #value,
            byte_big: #byte_big,
            word_big: #word_big,
            scale: #scale,
            offset_add: #offset_add,
            scale_ref: #scale_ref,
            selector: #selector,
            na: &[#(#na),*],
            access: #access,
            write: #write,
        }
    }
}
